DROP TABLE H_FMT_CODE;
DROP TABLE H_RULE;
DROP TABLE H_RULE_FIELD;
DROP TABLE H_TRAN_RULE;
DROP TABLE H_DIFF_RULE;
CREATE TABLE H_FMT_CODE
(
  UUID          VARCHAR(40) NOT NULL,
  TRAN_CODE     VARCHAR(50) NOT NULL,
  MSG_SEQ       INTEGER(9) NOT NULL,
  REQUEST_TIME  VARCHAR(20) NOT NULL,
  RESPONSE_TIME VARCHAR(20),
  FLAG          CHAR(1) DEFAULT 0 NOT NULL,
  STATUS        CHAR(1) NOT NULL,
  DIFF_RESULT     VARCHAR(1),
  DIFF_INFO     VARCHAR(10240)
);
CREATE TABLE H_RULE
(
  ID          INTEGER NOT NULL,
  RULE_CODE   VARCHAR(20) NOT NULL,
  RULE_NAME   VARCHAR(100) NOT NULL,
  RULE_TYPE   VARCHAR(30) NOT NULL,
  FUNC_CLASS  VARCHAR(150) NOT NULL,
  RESULT_MODE VARCHAR(1) NOT NULL,
  REMARK      VARCHAR(100)
);
CREATE TABLE H_RULE_FIELD
(
  ID        INTEGER NOT NULL,
  RULE_CODE VARCHAR(20) NOT NULL,
  ELE_CODE  VARCHAR(50) NOT NULL,
  CMP_TYPE  VARCHAR(50) NOT NULL,
  VALUE1    VARCHAR(50),
  VALUE2    VARCHAR(50),
  REMARK    VARCHAR(100) NOT NULL
);
CREATE TABLE H_TRAN_RULE
(
  ID         INTEGER NOT NULL,
  TRAN_CODE  VARCHAR(20) NOT NULL,
  RULE_CODE  VARCHAR(20) NOT NULL,
  RULE_LEVEL INTEGER NOT NULL
);
CREATE TABLE H_DIFF_RULE
(
  ID        INTEGER NOT NULL,
  TRAN_CODE VARCHAR(20) NOT NULL,
  ELE_CODE  VARCHAR(50) NOT NULL,
  DESELECT_FLAG BOOLEAN DEFAULT 0 NOT NULL,
  CMP_TYPE  VARCHAR(50) NOT NULL,
  VALUE1    VARCHAR(50),
  VALUE2    VARCHAR(50),
  REMARK    VARCHAR(100) NOT NULL
);